---
sudo: required

language: node_js

node_js:
  - "7"

services:
  - docker

jobs:
  include:
    - stage: lint
      install:
        - npm install -g dockerlint
      script:
        - dockerlint tideways-daemon/Dockerfile
        - dockerlint tideways-proxy/Dockerfile

    - stage: build
      script:
        - docker build tideways-daemon
        - docker build tideways-proxy
